# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-07 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubiwhere_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datafromsensor',
            table='data_from_sensors',
        ),
    ]
