# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-12 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiwhere_app', '0003_auto_20191108_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafromsensor',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datafromsensor',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafromsensor',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafromsensor',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datafromsensor',
            name='geo_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datafromsensor',
            name='state',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datafromsensor',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
