# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-13 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiwhere_app', '0004_auto_20191112_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafromsensor',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='datafromsensor',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
